version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
    restart: always
