version: '3'

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
        #- ./requirements/nginx/html/:/var/www/html/
      - ./requirements/nginx/html/:/usr/share/nginx/html/
    restart: always
